/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppTabbar: typeof import('./src/components/AppTabbar.vue')['default'];
    FixedBottom: typeof import('./src/components/FixedBottom.vue')['default'];
    ImmersiveBottomBar: typeof import('./src/components/ImmersiveBottomBar.vue')['default'];
    ImmersiveNavbar: typeof import('./src/components/ImmersiveNavbar.vue')['default'];
    MapNavigationButton: typeof import('./src/components/MapNavigationButton.vue')['default'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    VanCell: typeof import('vant/es')['Cell'];
    VanCellGroup: typeof import('vant/es')['CellGroup'];
    VanNavBar: typeof import('vant/es')['NavBar'];
    VanTabbar: typeof import('vant/es')['Tabbar'];
    VanTabbarItem: typeof import('vant/es')['TabbarItem'];
  }
}
